<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>RevitFlexConduitInstaller.Program301</StartupObject>
    <AssemblyName>RevitFlexConduit2025-v3.0.1-Setup</AssemblyName>
    <RootNamespace>RevitFlexConduitInstaller</RootNamespace>
    <Version>3.0.1</Version>
    <AssemblyVersion>3.0.1.0</AssemblyVersion>
    <FileVersion>3.0.1.0</FileVersion>
    <InformationalVersion>3.0.1</InformationalVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Payload\RevitFlexConduit.dll" LogicalName="Payload.RevitFlexConduit.dll" />
  </ItemGroup>
</Project>
